# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

autotune_lasso <- function(xin, yin, alpha = 0.01, lambda0 = NULL, tolerance = 1e-4, beta_tolerance = 1e-3, iter_max = 30L, beta_iter_max = 40L, standardize = TRUE, standardize_response = TRUE, intercept = TRUE, active = FALSE, verbose = FALSE, l2_partial_residuals = FALSE) {
    .Call(`_Autotune_autotune_lasso`, xin, yin, alpha, lambda0, tolerance, beta_tolerance, iter_max, beta_iter_max, standardize, standardize_response, intercept, active, verbose, l2_partial_residuals)
}

