# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

autotune_lasso <- function(xin, yin, alpha = 0.01, standardize = TRUE, standardize_response = TRUE, intercept = TRUE, trace_it = FALSE, tolerance = 1e-4, beta_tolerance = 1e-3, iter_max = 30L, beta_iter_max = 40L, active = FALSE, PR_norm_l2 = FALSE) {
    .Call(`_autotune_autotune_lasso`, xin, yin, alpha, standardize, standardize_response, intercept, trace_it, tolerance, beta_tolerance, iter_max, beta_iter_max, active, PR_norm_l2)
}

